# Generated by Django 4.0.5 on 2022-08-07 10:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('jcategory', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Job category',
                'verbose_name_plural': 'Job categories',
            },
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=150)),
                ('job_type', models.CharField(choices=[('Intern', 'Intern'), ('Part-time', 'Part-time'), ('Remote', 'Remote'), ('Full-time', 'Full-time'), ('Hybrid', 'Hybrid')], max_length=150)),
                ('company', models.CharField(max_length=50)),
                ('Company_logo', models.ImageField(upload_to='logos/% Y/% m/% d/')),
                ('location', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=250)),
                ('job_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.categories')),
            ],
        ),
    ]
